import type { Stylesheet } from "cytoscape";
import { nodeVisuals } from "./node-visuals";

const elevatedNodeShadowStyle = {
  "shadow-blur": 10,
  "shadow-color": "#010409",
  "shadow-offset-y": 4,
  "shadow-offset-x": 0,
  "shadow-opacity": 0.5,
} as const;

export const cytoscapeStyle: Stylesheet[] = [
  {
    selector: "node.cluster",
    style: {
      shape: "round-rectangle",
      "background-color": "#161b22",
      "border-color": "data(color)",
      "border-width": 3,
      "background-image": nodeVisuals.cluster.iconDataUri,
      "background-width": "18px",
      "background-height": "18px",
      "background-position-x": "12px",
      "background-position-y": "12px",
      "background-clip": "none",
      "background-image-opacity": 0.6,
      label: "data(label)",
      "text-valign": "center",
      "text-halign": "center",
      color: "#e6edf3",
      "font-size": "14px",
      width: 160,
      height: 80,
      "text-wrap": "wrap",
      "text-max-width": "140px",
      padding: "10px",
      cursor: "pointer",
      ...elevatedNodeShadowStyle,
    },
  },
  {
    selector: "node.system",
    style: {
      shape: "round-rectangle",
      "background-color": "#161b22",
      "border-color": "data(color)",
      "border-width": 3,
      "background-image": nodeVisuals.system.iconDataUri,
      "background-width": "18px",
      "background-height": "18px",
      "background-position-x": "12px",
      "background-position-y": "12px",
      "background-clip": "none",
      "background-image-opacity": 0.6,
      label: "data(label)",
      "text-valign": "center",
      "text-halign": "center",
      color: "#e6edf3",
      "font-size": "13px",
      width: 150,
      height: 70,
      "text-wrap": "wrap",
      "text-max-width": "130px",
      cursor: "pointer",
      ...elevatedNodeShadowStyle,
    },
  },
  {
    selector: "node.external",
    style: {
      shape: "round-rectangle",
      "background-color": "#0d1117",
      "border-color": "#30363d",
      "border-width": 1,
      "border-style": "dashed",
      "background-image": nodeVisuals.external.iconDataUri,
      "background-width": "18px",
      "background-height": "18px",
      "background-position-x": "12px",
      "background-position-y": "50%",
      "background-clip": "none",
      "background-image-opacity": 0.6,
      label: "data(label)",
      "text-valign": "center",
      "text-halign": "center",
      "text-margin-x": 10,
      color: "#6e7681",
      "font-size": "12px",
      width: 130,
      height: 60,
      opacity: 0.7,
      ...elevatedNodeShadowStyle,
    },
  },
  {
    selector: "node.store",
    style: {
      shape: "barrel",
      "background-color": "#1a1a10",
      "border-color": "#d29922",
      "border-width": 2,
      "background-image": nodeVisuals.store.iconDataUri,
      "background-width": "18px",
      "background-height": "18px",
      "background-position-x": "12px",
      "background-position-y": "50%",
      "background-clip": "none",
      "background-image-opacity": 0.6,
      label: "data(label)",
      "text-valign": "center",
      "text-halign": "center",
      "text-margin-x": 10,
      color: "#e6edf3",
      "font-size": "12px",
      width: 120,
      height: 60,
      cursor: "pointer",
      ...elevatedNodeShadowStyle,
    },
  },
  {
    selector: "node.behavioral-lifecycle",
    style: {
      shape: "round-rectangle",
      "background-color": "#18222d",
      "border-color": "#58a6ff",
      "border-width": 3.5,
      "background-image": nodeVisuals["behavioral-lifecycle"].iconDataUri,
      "background-width": "18px",
      "background-height": "18px",
      "background-position-x": "12px",
      "background-position-y": "12px",
      "background-clip": "none",
      "background-image-opacity": 0.6,
      label: "data(label)",
      "text-valign": "center",
      "text-halign": "center",
      color: "#e6edf3",
      "font-size": "13px",
      width: 210,
      height: 92,
      "text-wrap": "wrap",
      "text-max-width": "180px",
      padding: "10px",
      cursor: "pointer",
      ...elevatedNodeShadowStyle,
    },
  },
  {
    selector: "node.behavioral-stage",
    style: {
      shape: "round-rectangle",
      "background-color": "#202736",
      "border-color": "#4fa9a0",
      "border-width": 3,
      "background-image": nodeVisuals["behavioral-stage"].iconDataUri,
      "background-width": "18px",
      "background-height": "18px",
      "background-position-x": "12px",
      "background-position-y": "12px",
      "background-clip": "none",
      "background-image-opacity": 0.6,
      label: "data(label)",
      "text-valign": "center",
      "text-halign": "center",
      color: "#e6edf3",
      "font-size": "12px",
      width: 180,
      height: 74,
      "text-wrap": "wrap",
      "text-max-width": "160px",
      cursor: "pointer",
      ...elevatedNodeShadowStyle,
    },
  },
  {
    selector: "node.behavioral-step",
    style: {
      shape: "round-rectangle",
      "background-color": "#251f2f",
      "border-color": "#d29922",
      "border-width": 2,
      "background-image": nodeVisuals["behavioral-step"].iconDataUri,
      "background-width": "18px",
      "background-height": "18px",
      "background-position-x": "12px",
      "background-position-y": "50%",
      "background-clip": "none",
      "background-image-opacity": 0.6,
      label: "data(label)",
      "text-valign": "center",
      "text-halign": "center",
      "text-margin-x": 10,
      color: "#e6edf3",
      "font-size": "11px",
      width: 170,
      height: 64,
      "text-wrap": "wrap",
      "text-max-width": "150px",
      cursor: "pointer",
      ...elevatedNodeShadowStyle,
    },
  },
  {
    selector: "edge.cluster-edge",
    style: {
      "curve-style": "bezier",
      "control-point-step-size": 40,
      "target-arrow-shape": "triangle",
      "line-color": "#30363d",
      "target-arrow-color": "#30363d",
      width: 2,
      label: "data(label)",
      "font-size": "10px",
      color: "#6e7681",
      "text-background-color": "#0d1117",
      "text-background-opacity": 0.8,
      "text-background-padding": "3px",
      cursor: "pointer",
    },
  },
  {
    selector: "edge.system-edge",
    style: {
      "curve-style": "bezier",
      "control-point-step-size": 40,
      "target-arrow-shape": "triangle",
      "line-color": "#484f58",
      "target-arrow-color": "#484f58",
      width: 2,
      label: "data(label)",
      "font-size": "9px",
      color: "#6e7681",
      "text-background-color": "#0d1117",
      "text-background-opacity": 0.8,
      "text-background-padding": "2px",
      cursor: "pointer",
    },
  },
  {
    selector: "edge.store-edge",
    style: {
      "curve-style": "bezier",
      "control-point-step-size": 40,
      "target-arrow-shape": "triangle",
      "line-color": "#d29922",
      "target-arrow-color": "#d29922",
      width: 1,
      "line-style": "dashed",
      opacity: 0.6,
      label: "data(label)",
      "font-size": "10px",
      color: "#d29922",
      "text-background-color": "#0d1117",
      "text-background-opacity": 0.8,
      "text-background-padding": "2px",
    },
  },
  {
    selector: "edge.behavioral-edge",
    style: {
      "curve-style": "bezier",
      "control-point-step-size": 8,
      "target-arrow-shape": "triangle",
      "target-arrow-fill": "filled",
      "line-color": "#4fa9a0",
      "target-arrow-color": "#4fa9a0",
      "arrow-scale": 1.25,
      width: 2.4,
      opacity: 0.92,
      label: "data(label)",
      "font-size": "11px",
      color: "#9aa4af",
      "text-max-width": "200px",
      "text-wrap": "wrap",
      "text-background-color": "#0d1117",
      "text-background-opacity": 0.95,
      "text-background-padding": "3px",
      "text-margin-y": "-8px",
      cursor: "pointer",
    },
  },
  {
    selector: "edge.behavioral-back-edge",
    style: {
      "curve-style": "unbundled-bezier",
      "control-point-distances": "140",
      "control-point-weights": "0.5",
      "line-style": "dashed",
      "line-color": "#d29922",
      "target-arrow-color": "#d29922",
      "target-arrow-shape": "triangle",
      width: 2,
      label: "data(label)",
      "font-size": "9px",
      color: "#d29922",
      "text-max-width": "120px",
      "text-wrap": "wrap",
      "text-background-color": "#0d1117",
      "text-background-opacity": 0.8,
      "text-background-padding": "2px",
    },
  },
  {
    selector: "node.module-group",
    style: {
      shape: "round-rectangle",
      "background-color": "rgba(22, 27, 34, 0.5)",
      "border-color": "#30363d",
      "border-width": 1,
      label: "data(label)",
      "text-valign": "top",
      "text-halign": "center",
      color: "#9aa4af",
      "font-size": "11px",
      padding: "18px",
      "text-margin-y": "-4px",
      events: "no",
    } as any,
  },
  {
    selector: "node.file-node",
    style: {
      shape: "round-rectangle",
      "background-color": "#161b22",
      "border-color": "data(color)",
      "border-width": 2,
      "background-image": nodeVisuals["file-node"].iconDataUri,
      "background-width": "18px",
      "background-height": "18px",
      "background-position-x": "12px",
      "background-position-y": "50%",
      "background-clip": "none",
      "background-image-opacity": 0.6,
      label: "data(label)",
      "text-valign": "center",
      "text-halign": "center",
      "text-margin-x": 10,
      color: "#e6edf3",
      "font-size": "11px",
      width: 130,
      height: 50,
      "text-wrap": "wrap",
      "text-max-width": "120px",
      cursor: "pointer",
      ...elevatedNodeShadowStyle,
    },
  },
  {
    selector: "node.agent-node",
    style: {
      shape: "hexagon",
      "background-color": "#1a1525",
      "border-color": "#9D7BEE",
      "border-width": 2,
      "background-image": nodeVisuals["agent-node"].iconDataUri,
      "background-width": "18px",
      "background-height": "18px",
      "background-position-x": "12px",
      "background-position-y": "50%",
      "background-clip": "none",
      "background-image-opacity": 0.6,
      label: "data(label)",
      "text-valign": "center",
      "text-halign": "center",
      "text-margin-x": 10,
      color: "#e6edf3",
      "font-size": "11px",
      width: 130,
      height: 50,
      cursor: "pointer",
      ...elevatedNodeShadowStyle,
    },
  },
  {
    selector: "node.panel-active",
    style: {
      "border-width": 3,
      "border-color": "#58a6ff",
      "border-style": "double",
    },
  },
  {
    selector: "node.zoom-dot:not(:parent)",
    style: {
      label: "",
      "background-image-opacity": 0,
      "shadow-opacity": 0,
    },
  },
  {
    selector: "node.zoom-icon:not(:parent)",
    style: {
      label: "",
      "shadow-opacity": 0,
    },
  },
  {
    selector: "node.zoom-label:not(:parent)",
    style: {
      "font-size": "10px",
    },
  },
  {
    selector: "edge.file-import",
    style: {
      "curve-style": "bezier",
      "control-point-step-size": 30,
      "target-arrow-shape": "triangle",
      "line-color": "#262b33",
      "target-arrow-color": "#262b33",
      width: 1,
      label: "data(label)",
      "font-size": "8px",
      color: "#6e7681",
      "text-background-color": "#0d1117",
      "text-background-opacity": 0.7,
      "text-background-padding": "2px",
    },
  },
  {
    selector: "edge.agent-invoke",
    style: {
      "curve-style": "bezier",
      "control-point-step-size": 40,
      "target-arrow-shape": "triangle",
      "line-color": "#9D7BEE",
      "target-arrow-color": "#9D7BEE",
      width: 1.5,
      "line-style": "dotted",
      label: "data(label)",
      "font-size": "8px",
      color: "#6e7681",
      "text-background-color": "#0d1117",
      "text-background-opacity": 0.7,
      "text-background-padding": "2px",
    },
  },
  {
    selector: "edge[_segmentWeights]",
    style: {
      "curve-style": "unbundled-bezier",
      "control-point-weights": "data(_segmentWeights)",
      "control-point-distances": "data(_segmentDistances)",
      "edge-distances": "node-position",
    },
  },
  {
    selector: "edge.zoom-hide-labels",
    style: {
      label: "",
    },
  },
  {
    selector: "node:active, node:selected",
    style: {
      "overlay-opacity": 0.1,
    },
  },
  {
    selector: ".highlighted",
    style: {
      "z-index": 999,
      "z-index-compare": "manual",
      "transition-property": "opacity",
      "transition-duration": "0.15s",
    },
  },
  {
    selector: "edge.highlighted",
    style: {
      width: 3,
      "z-index": 999,
      "z-index-compare": "manual",
      opacity: 1,
    },
  },
  {
    selector: "edge.flow-animated",
    style: {
      "line-style": "dashed",
      "line-dash-pattern": [10, 6],
      "line-dash-offset": 0,
    },
  },
  {
    selector: ".neighbor-highlighted",
    style: {
      opacity: 1,
      "z-index": 998,
      "z-index-compare": "manual",
    },
  },
  {
    selector: ".hover-hidden",
    style: {
      opacity: 0,
      "transition-property": "opacity",
      "transition-duration": "0.05s",
    },
  },
  {
    selector: ".dimmed",
    style: {
      opacity: 0.18,
      "transition-property": "opacity",
      "transition-duration": "0.3s",
    },
  },
  {
    selector: ".dimmed.highlighted, .dimmed.neighbor-highlighted",
    style: {
      opacity: 1,
    },
  },
  // Mermaid edge routing: when edges have segment data from mermaid layout,
  // override curve-style to unbundled-bezier with computed control points
  {
    selector: "edge[_segmentWeights]",
    style: {
      "curve-style": "unbundled-bezier",
      "control-point-weights": "data(_segmentWeights)",
      "control-point-distances": "data(_segmentDistances)",
      "edge-distances": "node-position",
    } as any,
  },
];
