import { createMemo, createSignal, type Accessor } from "solid-js";

import { createFocusStackService } from "./FocusStackService";
import type { TransportStoreType } from "./TransportStore";

// --- Scenario data types (generated by pipeline into diagram.json) ---

export type ScenarioBeat =
  | {
      id: string;
      kind: "path";
      caption?: string;
      fromNodeId: string;
      toNodeId: string;
      edgeIds: string[];
      participantNodeIds: string[];
      durationMs?: number;
    }
  | {
      id: string;
      kind: "subScenario";
      caption?: string;
      scenarioId: string;
      entryNodeId: string;
      exitNodeId?: string;
    };

export type CombinedScenario = {
  id: string;
  behaviorId: string;
  title: string;
  caption?: string;
  rootNodeId?: string;
  participants: string[];
  beats: ScenarioBeat[];
};

export type CombinedData = {
  scenarios: Record<string, CombinedScenario>;
  bindings: Record<string, string[]>;
};

// --- BehaviorPlaybackController ---

export type PlaybackStatus = "idle" | "loading" | "playing" | "paused" | "complete";

export function createBehaviorPlaybackController(
  scenarioData: Accessor<CombinedData | undefined>,
  transport: TransportStoreType,
) {
  const [activeScenarioId, setActiveScenarioId] = createSignal<string | null>(null);
  const [currentBeatIndex, setCurrentBeatIndex] = createSignal(0);
  const [status, setStatus] = createSignal<PlaybackStatus>("idle");
  const [lastError, setLastError] = createSignal<string | null>(null);
  const [bridgeActive, setBridgeActive] = createSignal(false);
  const [scopeTransition, setScopeTransition] = createSignal<{
    direction: "drill" | "back";
    anchorNodeId: string;
    targetScopeId?: string;
  } | null>(null);

  const focusStack = createFocusStackService();

  const scenario = createMemo(() => {
    const id = activeScenarioId();
    if (!id) return null;
    return scenarioData()?.scenarios[id] ?? null;
  });

  const currentBeat = createMemo(() => {
    const s = scenario();
    if (!s) return null;
    return s.beats[currentBeatIndex()] ?? null;
  });

  const captionText = createMemo(() => {
    const beat = currentBeat();
    if (!beat) return scenario()?.caption ?? "";
    return beat.caption ?? "";
  });

  const participants = createMemo(() => {
    const s = scenario();
    return new Set(s?.participants ?? []);
  });

  function loadBeatIntoTransport(beat: ScenarioBeat) {
    if (beat.kind !== "path") return;
    if (beat.edgeIds.length > 0) {
      transport.load(beat.fromNodeId);
    }
  }

  function loadScenario(scenarioId: string): boolean {
    const data = scenarioData();
    if (!data) return false;
    const s = data.scenarios[scenarioId];
    if (!s || s.beats.length === 0) return false;

    setActiveScenarioId(scenarioId);
    setCurrentBeatIndex(0);

    const firstBeat = s.beats[0];
    if (firstBeat.kind === "subScenario") {
      enterSubScenario(firstBeat);
    } else {
      loadBeatIntoTransport(firstBeat);
      transport.play();
    }
    return true;
  }

  function start(behaviorId: string) {
    const data = scenarioData();
    if (!data) {
      setLastError("No scenario data available");
      return;
    }

    const scenarioIds = data.bindings[behaviorId];
    if (!scenarioIds || scenarioIds.length === 0) {
      setLastError(`No scenario found for behavior: ${behaviorId}`);
      return;
    }

    setLastError(null);
    focusStack.clear();
    setStatus("playing");

    if (!loadScenario(scenarioIds[0])) {
      setLastError(`Scenario ${scenarioIds[0]} has no beats`);
      setStatus("idle");
    }
  }

  function enterSubScenario(beat: ScenarioBeat & { kind: "subScenario" }) {
    const currentScenario = scenario();
    if (!currentScenario) return;

    const pushed = focusStack.pushChild({
      scenarioId: beat.scenarioId,
      title: beat.caption ?? beat.scenarioId,
      parentScenarioId: currentScenario.id,
      parentBeatIndex: currentBeatIndex(),
      resumeBeatIndex: currentBeatIndex() + 1,
      entryNodeId: beat.entryNodeId,
      exitNodeId: beat.exitNodeId,
    });

    if (!pushed) {
      setLastError("Maximum sub-scenario depth reached");
      advanceBeat();
      return;
    }

    setBridgeActive(true);
    setScopeTransition({
      direction: "drill",
      anchorNodeId: beat.entryNodeId,
      targetScopeId: beat.scenarioId,
    });
    // GraphSurface reacts to scopeTransition and runs GSAP drill.
    // After animation, it calls onScopeTransitionComplete().
    setTimeout(() => {
      setBridgeActive(false);
      setScopeTransition(null);
      loadScenario(beat.scenarioId);
    }, 500);
  }

  function completeScenario() {
    if (focusStack.depth() > 0) {
      resumeParent();
    } else {
      setStatus("complete");
      transport.pause();
    }
  }

  function resumeParent() {
    const frame = focusStack.pop();
    if (!frame || !frame.parentScenarioId) {
      setStatus("complete");
      transport.pause();
      return;
    }

    setBridgeActive(true);
    setScopeTransition({
      direction: "back",
      anchorNodeId: frame.entryNodeId,
      targetScopeId: frame.parentScenarioId ?? undefined,
    });
    setTimeout(() => {
      setBridgeActive(false);
      setScopeTransition(null);
      setActiveScenarioId(frame.parentScenarioId);
      setCurrentBeatIndex(frame.resumeBeatIndex);

      const s = scenarioData()?.scenarios[frame.parentScenarioId!];
      if (!s || frame.resumeBeatIndex >= s.beats.length) {
        completeScenario();
        return;
      }

      const beat = s.beats[frame.resumeBeatIndex];
      if (beat.kind === "subScenario") {
        enterSubScenario(beat);
      } else {
        loadBeatIntoTransport(beat);
        transport.play();
      }
    }, 400);
  }

  function advanceBeat() {
    const s = scenario();
    if (!s) return;

    const nextIndex = currentBeatIndex() + 1;
    if (nextIndex >= s.beats.length) {
      completeScenario();
      return;
    }

    setCurrentBeatIndex(nextIndex);
    const beat = s.beats[nextIndex];

    if (beat.kind === "subScenario") {
      enterSubScenario(beat);
    } else {
      loadBeatIntoTransport(beat);
      transport.play();
    }
  }

  function stop() {
    transport.reset();
    focusStack.clear();
    setActiveScenarioId(null);
    setCurrentBeatIndex(0);
    setStatus("idle");
    setLastError(null);
    setBridgeActive(false);
    setScopeTransition(null);
  }

  function pause() {
    transport.pause();
    setStatus("paused");
  }

  function resume() {
    transport.play();
    setStatus("playing");
  }

  return {
    activeScenarioId,
    scenario,
    currentBeatIndex,
    currentBeat,
    captionText,
    participants,
    status,
    lastError,
    bridgeActive,
    scopeTransition,
    focusStack,
    start,
    advanceBeat,
    stop,
    pause,
    resume,
  };
}

export type BehaviorPlaybackControllerType = ReturnType<typeof createBehaviorPlaybackController>;
